default:
  # ---- To be processed by Ellis lanes
  # path_pt_1_raw                  :"data-public/raw/pt-1.csv"

  # path_ss_county                 : "data-public/metadata/ss-county.csv"
  path_metadata_concept            : "data-public/metadata/concept.csv"
  path_metadata_concept_simulate   : "data-public/metadata/concept-to-simulate.csv"

  # Central Database (produced by Ellis lanes).
  path_database_duckdb             : "data-public/derived/duckdb/db.duckdb"
  path_database_sqlite             : "data-public/derived/sqlite/db.sqlite3"

  # ---- Simulated-ready datasets (consumed by scribes).
  path_csv_site                    : "data-public/derived/csv/site_latent.csv"
  path_csv_observation             : "data-public/derived/csv/observation.csv"
  path_csv_person                  : "data-public/derived/csv/person.csv"
  path_csv_patient_ll              : "data-public/derived/csv/patient_ll.csv"
  path_csv_patient_hidden          : "data-public/derived/csv/patient_latent.csv"

  path_parquet_site                : "data-public/derived/parquet/site_latent.parquet"
  path_parquet_observation         : "data-public/derived/parquet/observation.parquet"
  path_parquet_person              : "data-public/derived/parquet/person.parquet"
  path_parquet_patient_ll          : "data-public/derived/parquet/patient_ll.parquet"
  path_parquet_patient_hidden      : "data-public/derived/parquet/patient_latent.parquet"

  path_rds_site                    : "data-public/derived/rds/site_latent.rds"
  path_rds_observation             : "data-public/derived/rds/observation.rds"
  path_rds_person                  : "data-public/derived/rds/person.rds"
  path_rds_patient_ll              : "data-public/derived/rds/patient_ll.rds"
  path_rds_patient_hidden          : "data-public/derived/rds/patient_latent.rds"

  # ---- Analysis-ready datasets (produced by scribes & consumed by analyses).
  path_analysis_patient_csv        : "data-public/derived/analysis/patient.csv"
  path_analysis_patient_parquet    : "data-public/derived/analysis/patient.parquet"

  path_log_flow:              !expr strftime(Sys.time(), "data-unshared/log/%Y/%Y-%m/flow-%Y-%m-%d--%H-%M-%S.log")

  produce_csv                   : true
  produce_duckdb                : true
  produce_parquet               : true
  produce_rds                   : true
  produce_sqlite                : true

  # ---- Constants
  covid_start_nation            : !expr as.Date("2020-01-01")
  boundary_date_max             : !expr as.Date("2022-12-31")
  # time_zone_local:          "America/Chicago"          # Force time calculations to be local, in case remotely run from another timezone.  See ?base::Sys.timezone()

  # ---- Validation Ranges & Patterns
  range_person_id               : !expr c(1L, 999999L)
  # range_cpt4                    : !expr c(10000L, 99999L)
  omop_concept_min              : 0
  omop_concept_local            : 2000000000
  omop_concept_max              : 2147483647
