default:
  # ---- To be processed by Ellis lanes
  # path_subject_1_raw:       "data-public/raw/subject-1.csv"

  # path_ss_county:           "data-public/metadata/ss-county.csv"
  path_metadata_concept:      "data-public/metadata/concept.csv"

  # Central Database (produced by Ellis lanes).
  path_database_duckdb:               "data-public/derived/duckdb/db.duckdb"
  path_database_sqlite:               "data-public/derived/sqlite/db.sqlite3"

  # ---- Simulated-ready datasets (consumed by scribes).
  path_csv_site                    : "data-public/derived/csv/site.csv"
  path_csv_person                  : "data-public/derived/csv/person.csv"
  path_csv_patient                 : "data-public/derived/csv/patient.csv"
  path_csv_patient_hidden          : "data-public/derived/csv/patient-hidden.csv"

  path_parquet_site                : "data-public/derived/parquet/site.parquet"
  path_parquet_person              : "data-public/derived/parquet/person.parquet"
  path_parquet_patient             : "data-public/derived/parquet/patient.parquet"
  path_parquet_patient_hidden      : "data-public/derived/parquet/patient-hidden.parquet"

  path_rds_site                    : "data-public/derived/rds/site.rds"
  path_rds_person                  : "data-public/derived/rds/person.rds"
  path_rds_patient                 : "data-public/derived/rds/patient.rds"
  path_rds_patient_hidden          : "data-public/derived/rds/patient-hidden.rds"

  # ---- Analysis-ready datasets (produced by scribes & consumed by analyses).
  path_analysis_patient_csv        : "data-public/derived/analysis/patient.csv"
  path_analysis_patient_rds        : "data-public/derived/analysis/patient.rds"

  path_log_flow:              !expr strftime(Sys.time(), "data-unshared/log/%Y/%Y-%m/flow-%Y-%m-%d--%H-%M-%S.log")

  produce_csv                   : true
  produce_duckdb                : true
  produce_parquet               : true
  produce_rds                   : true
  produce_sqlite                : true

  # ---- Constants
  covid_start_nation            : !expr as.Date("2020-01-01")
  boundary_date_max             : !expr as.Date("2022-12-31")
  # time_zone_local:          "America/Chicago"          # Force time calculations to be local, in case remotely run from another timezone.  See ?base::Sys.timezone()

  # ---- Validation Ranges & Patterns
  range_person_id               : !expr c(1L, 999999L)
  # range_cpt4                    : !expr c(10000L, 99999L)
  omop_concept_min              : 0
  omop_concept_local            : 2000000000
  omop_concept_max              : 2147483647
