default:
  # ---- To be processed by Ellis lanes
  # path_subject_1_raw:       "data-public/raw/subject-1.csv"

  # path_ss_county:           "data-public/metadata/ss-county.csv"
  path_metadata_concept:      "data-public/metadata/concept.csv"

  # Central Database (produced by Ellis lanes).
  path_database:              "data-public/derived/db.sqlite3"

  # ---- Simulated-ready datasets (consumed by scribes).
  path_simulated_site_csv:            "data-public/simulated/site.csv"
  path_simulated_patient_csv:         "data-public/simulated/patient.csv"
  path_simulated_patient_rds:         "data-public/simulated/patient.rds"
  path_simulated_person_hidden_csv:   "data-public/simulated/person-hidden.csv"
  path_simulated_person_hidden_rds:   "data-public/simulated/person-hidden.rds"

  # ---- Analysis-ready datasets (produced by scribes & consumed by analyses).
  path_derived_person_csv:        "data-public/derived/person.csv"
  path_derived_person_rds:        "data-public/derived/person.rds"

  path_log_flow:              !expr strftime(Sys.time(), "data-unshared/log/%Y/%Y-%m/flow-%Y-%m-%d--%H-%M-%S.log")

  # ---- Constants
  covid_start_nation            : !expr as.Date("2020-01-01")
  boundary_date_max             : !expr as.Date("2022-12-31")
  # time_zone_local:          "America/Chicago"          # Force time calculations to be local, in case remotely run from another timezone.  See ?base::Sys.timezone()

  # ---- Validation Ranges & Patterns
  range_person_id               : !expr c(1L, 999999L)
  # range_cpt4                    : !expr c(10000L, 99999L)
  omop_concept_min              : 0
  omop_concept_local            : 2000000000
  omop_concept_max              : 2147483647
